version: 2
updates:
- package-ecosystem: nuget
  directory: "/Ghpr.NUnit"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
